DEVICE_ID: 0
MODEL:
  NAME: DenseMLP3
  NUM_BLOCKS: 2
  NUM_HIDDEN_LAYERS: 5
  NUM_HIDDEN_NEURONS: 1024
NUM_EXPERIMENT_REPETITIONS: 1
ROBOT_CHOICE: 7DoF-7R-Panda
SEED_CHOICE: true
SEED_NUMBER: 0
TRAIN:
  CHECKPOINT:
    LOAD_OPTIONS: local
    PRETRAINED_G_MODEL: ''
    RESUMED_G_MODEL: ''
    SAVE_OPTIONS: cloud
  DATASET:
    JOINT_LIMIT_SCALE: 10
    JOINT_VARIATION: 1
    NUM_SAMPLES: 1000000
    ORIENTATION: RPY
    TYPE: seq
  HYPERPARAMETERS:
    BATCH_SIZE: 128
    BETAS:
    - 0.9
    - 0.999
    EPOCHS: 1000
    EPS: 1.0e-05
    LEARNING_RATE: 0.0001
    LOSS: lq
    NUM_WORKERS: 4
    OPTIMIZER_NAME: Adam
    PERSISTENT_WORKERS: true
    PIN_MEMORY: false
    SHUFFLE: true
    WEIGHT_DECAY: 0.0
    WEIGHT_INITIALIZATION: default
  PRINT_EPOCHS: true
  PRINT_STEPS: 100
