DEVICE_ID: 1
MODEL:
  NAME: MLP
  NUM_HIDDEN_LAYERS: 3
  NUM_HIDDEN_NEURONS: 1000
NUM_EXPERIMENT_REPETITIONS: 1
ROBOT_CHOICE: 7DoF-7R-Panda
SEED_CHOICE: true
SEED_NUMBER: 0
TRAIN:
  CHECKPOINT:
    PRETRAINED_G_MODEL: ''
    RESUMED_G_MODEL: ''
  DATASET:
    JOINT_LIMIT_SCALE: 8
    NUM_SAMPLES: 10000
  HYPERPARAMETERS:
    BATCH_SIZE: 128
    BETAS:
    - 0.9
    - 0.999
    EPOCHS: 10000
    EPS: 0.0001
    LEARNING_RATE: 0.0001
    LOSS: l2
    NUM_WORKERS: 4
    OPTIMIZER_NAME: SGD
    PERSISTENT_WORKERS: true
    PIN_MEMORY: true
    SHUFFLE: true
    WEIGHT_DECAY: 0.0
    WEIGHT_INITIALIZATION: default
  PRINT_EPOCHS: true
  PRINT_STEPS: 10
